### PR TITLE
Multiple miner instances within one executable

### PR DESCRIPTION
**Pull request by MichaelBell**
Ability to run multiple instances of the miner internally, sharing the same precomputed data.  This allows the throughput problems to be overcome even for high core counts and low difficulties.

### CODE REVIEW

**Comment by Pttn** [comment]
Sorry, I still get the same performance issues as discussed in the Riecoin Community Forum (that is right now broken?!). Did you really get satisfactory results in your side?

**Comment by MichaelBell** [comment]
How strange, I saw if anything slightly better single instance performance with the new code.  I'll double check and report some numbers.

**Comment by MichaelBell** [comment]
I've done a longer test run at Sieve = 2^31 and difficulty 1600 and it looks like I am seeing a 0.5-1% reduction in performance, I think I'd be happy to say that's a worthwhile tradeoff, but I'm not sure of the cause.  How big a difference do you see?

Note that you changed the default Sieve Max from 2^31 to 2^30 on master, so watch out for that when testing.

If you're seeing a >1% difference with the same parameters, please could you uncomment the "Block timing" output in MinerInstance::process() and paste some representative examples from master and this branch, as that will show which part of the processing is slower on your hardware/configuration.  Thanks!

Hopefully the forum will be back soon...

**Comment by Pttn** [comment]
I test mostly cases where your code will be actually useful: when the CPU Underuse Bug is present, i. e. when Difficulty is low and Sieve very high.

A representative situation is Difficulty = 1400 and Sieve = 2^32, where the CPU Underuse is significant: it is about the current mining difficulty, and a Sieve that is a good one for my computer. I will let you analyze these benchmarks (history with Block timing):

rieMiner with your code: https://pastebin.com/VMwjVawh
rieMiner 0.9b3.1: https://pastebin.com/Td8dGJx2

With the history, you can feel how precise are the results. In our case, the 1-tuples/s metric is the most significant one and should be taken as reference.

We have a 1.7% performance loss for the Standard Benchmark with Sieve 2^31, and 1 x 16 threads for both (226.5 pps vs 222.7 pps).
For the more practical case (Difficulty 1400, Sieve 2^32, 2 x 8), it is worse: 340.0 pps vs 330.4 pps (2,9%).

The fact that your code has a performance loss is reproducible. I never get better results with your code, even for the basic case of 1 x 16 threads that is not suffering from the CPU Underuse. And after reviewing it, I think that your performance fix commit would actually not fix anything.

I hope that you will eventually find the cause of this. But maybe it is just impossible to do such thing without a significant overhead, and I am not adding a feature that causes a measurable performance loss.

Also, I just thought about another approach, would it be possible to always do in some way 1 Thread = 1 Instance of 1 Thread ("Thread = n" will launch n instances of 1 thread)? The user would not even have to specify the instances and the fix would be transparent.

But is your code copying the sieve and precomputed data for each instance? I thought that is was not the case, but my system (32 GB) became out of memory when I tried to do 16 x 1 thread (Sieve 2^31), while I thought that every instance shared the same sieve and precomputed data. In this case, there is no real point to add this feature, and the user can always write itself a script to start multiple instances if needed. The aim is to run multiple instances without duplicating these huge amount of data.

**Comment by MichaelBell** [comment]
For the record I see a noticeable improvement in the time to run updateRemainders (the first of the block timing numbers) with the performance fix.  However, I agree that whether this makes a difference could depend on the compiler, as it's just hinting that it shouldn't do extra pointer dereferences in the loops.

I'm surprised your block timing is so variable during the benchmark tests, I think this might hint at the problem - I believe you're testing on a Ryzen CPU, which apparently is basically two 4 core/8 thread CPUs with a (relatively) low bandwidth link between them.  With 2 instances running in one process the threads working on the same data won't be tied to a single CPU, whereas apparently Linux is reasonable at ensuring threads on the same process are scheduled on the same CPU as each other.

On memory usage, the instances within the process share the table of primes and the precomputed division data, but (obviously!) all the data associated with testing a particular block is per-instance, which is something in the region of 768MB + 16 bytes/prime.

I'm a bit surprised you're not a little more enthusiastic about this change - have you not realised this means you can sieve much more deeply while occupying your 16 threads, thus improving your 6-tuple find rate for a machine with fixed memory?  If you don't care about it I'm happy to drop it for now, as I only have 8 thread machines available to me.

**Comment by Pttn** [comment]
Avoiding to run manually multiple instances and saving a lot of memory is good, but not if there is a clear performance loss in equivalent situations, even if, like you said, I could try to use a Sieve of 1.5*2^32 and more to reduce the ratios and compensate. I would still be happy to merge this if you find a way to fix the loss. Yes, I am using a 2700X (@4 GHz when I test).

And actually, I feel that our fix with multiple instances is more a workaround than a real fix, though it is still better than nothing, if there were no performance loss. Maybe the threading logic has to be completely rewritten from scratch like IGJ said once, this option should be explored.

I hope that you do not take it badly if I refuse for now to merge your code, I am in any case grateful for your work. The performance loss is the only thing that prevents me from merging. If you find another solution than the multiple instance idea, open a new pull request, and this one will be closed.

**Comment by MichaelBell** [comment]
OK, quite understand you not want to merge code that introduces a performance loss!

I was hoping for a quick win here by allowing instances to share data, but it seems that hasn't worked out.  I agree that this solution was never ideal (although given potential issues with data crossing between cores an approach like this might end up being better than fully sharing data across all threads).  If you wanted to try to take this forwards it might be worth trying to set thread affinities and see if that improves the situation, but I'm not going to try that when I don't have a machine exhibiting the problem.

To go forwards, as you/IGJ suggest, I think we'd need to replace the simplistic thread queuing system with a better scheduler that can understand job dependencies, and move the scanning and scheduling work from the "main" thread into jobs.  I'm not interested in working on that right now though.

Happy to close this PR.

**Pull request closed without merging**
